const questions = [
    { question: "What is the capital of France?", answer: "Paris" },
    { question: "What is 2 + 2?", answer: "4" },
    { question: "What is the largest planet in our solar system?", answer: "Jupiter" },
    { question: "Who wrote 'Romeo and Juliet'?", answer: "William Shakespeare" },
    { question: "What is the boiling point of water in Celsius?", answer: "100" },
    { question: "What is the chemical symbol for gold?", answer: "Au" },
    { question: "Who painted the Mona Lisa?", answer: "Leonardo da Vinci" },
    { question: "What is the smallest prime number?", answer: "2" },
    { question: "What is the capital of Japan?", answer: "Tokyo" },
    { question: "What is the square root of 64?", answer: "8" },
    { question: "Who discovered gravity?", answer: "Isaac Newton" },
    { question: "What is the largest mammal?", answer: "Blue Whale" },
    { question: "What is the capital of Italy?", answer: "Rome" },
    { question: "What is the speed of light in vacuum (m/s)?", answer: "299,792,458" },
    { question: "Who is known as the father of computers?", answer: "Charles Babbage" },
    { question: "What is the capital of Germany?", answer: "Berlin" },
    { question: "What is the hardest natural substance on Earth?", answer: "Diamond" },
    { question: "What is the chemical formula for water?", answer: "H2O" },
    { question: "What is the capital of Canada?", answer: "Ottawa" },
    { question: "What is the largest ocean on Earth?", answer: "Pacific Ocean" },
    { question: "What is the capital of Australia?", answer: "Canberra" },
    { question: "What is the freezing point of water in Celsius?", answer: "0" },
    { question: "Who developed the theory of relativity?", answer: "Albert Einstein" },
    { question: "What is the capital of India?", answer: "New Delhi" },
    { question: "What is the tallest mountain in the world?", answer: "Mount Everest" },
];

export default questions;